using System;
using System.Collections.Generic;

namespace GB
{
    public static class Opcodes
    {
        public static readonly Dictionary<byte, Opcode> List = new Dictionary<byte, Opcode>
        {
            { 0x00, new Opcode("NOP", 1, 4, null, null) },
            { 0x02, new Opcode("LD (BC),A", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(BC)", "A"}) },
            { 0x04, new Opcode("INC B", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"B"}) },
            { 0x05, new Opcode("DEC B", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"B"}) },
            { 0x06, new Opcode("LD B,d8", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "d8"}) },
            { 0x0A, new Opcode("LD A,(BC)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(BC)"}) },
            { 0x0C, new Opcode("INC C", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"C"}) },
            { 0x0D, new Opcode("DEC C", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"C"}) },
            { 0x0E, new Opcode("LD C,d8", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "d8"}) },
            { 0x12, new Opcode("LD (DE),A", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(DE)", "A"}) },
            { 0x14, new Opcode("INC D", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"D"}) },
            { 0x15, new Opcode("DEC D", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"D"}) },
            { 0x16, new Opcode("LD D,d8 ", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "d8"}) },
            { 0x18, new Opcode("JR r8", 2, 0, 12, new OpcodeHandler(FlowCtrl.JMP), new List<string>{"r8"}) },
            { 0x1A, new Opcode("LD A,(DE)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(DE)"}) },
            { 0x1C, new Opcode("INC E", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"E"}) },
            { 0x1D, new Opcode("DEC E", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"E"}) },
            { 0x1E, new Opcode("LD E,d8", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "d8"}) },
            { 0x20, new Opcode("JR NZ,r8", 2, 0, 8, new OpcodeHandler(FlowCtrl.JMP), new List<string>{"NZ", "r8"}) },
            { 0x21, new Opcode("LD HL,d16", 3, 12, new OpcodeHandler(LDSTMV16.LD), new List<string>{"HL", "d16"}) },
            { 0x22, new Opcode("LD (HL+),A", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL+)", "A"}) },
            { 0x24, new Opcode("INC H", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"H"}) },
            { 0x25, new Opcode("DEC H", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"H"}) },
            { 0x26, new Opcode("LD H,d8 ", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "d8"}) },
            { 0x28, new Opcode("JR Z,r8", 2, 0, 12, new OpcodeHandler(FlowCtrl.JMP), new List<string>{"Z", "r8"}) },
            { 0x2A, new Opcode("LD A,(HL+)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(HL+)"}) },
            { 0x2C, new Opcode("INC L", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"L"}) },
            { 0x2D, new Opcode("DEC L", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"L"}) },
            { 0x2E, new Opcode("LD L,d8", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "d8"}) },
            { 0x31, new Opcode("LD SP,d16", 3, 13, new OpcodeHandler(LDSTMV16.LD), new List<string>{"SP", "d16"}) },
            { 0x32, new Opcode("LD (HL-),A", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL-)", "A"}) },
            { 0x34, new Opcode("INC (HL)", 1, 12, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"(HL)"}) },
            { 0x35, new Opcode("DEC (HL)", 1, 12, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"(HL)"}) },
            { 0x36, new Opcode("LD (HL),d8 ", 2, 12, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "d8"}) },
            { 0x38, new Opcode("JR C,r8", 2, 0, 12, new OpcodeHandler(FlowCtrl.JMP), new List<string>{"C", "r8"}) },
            { 0x3A, new Opcode("LD A,(HL-)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(HL-)"}) },
            { 0x3C, new Opcode("INC A", 1, 4, new OpcodeHandler(ARTHLOG8.INC), new List<string>{"A"}) },
            { 0x3D, new Opcode("DEC A", 1, 4, new OpcodeHandler(ARTHLOG8.DEC), new List<string>{"A"}) },
            { 0x3E, new Opcode("LD A,d8", 2, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "d8"}) },
            { 0x40, new Opcode("LD B,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "B"}) },
            { 0x41, new Opcode("LD B,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "C"}) },
            { 0x42, new Opcode("LD B,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "D"}) },
            { 0x43, new Opcode("LD B,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "E"}) },
            { 0x44, new Opcode("LD B,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "H"}) },
            { 0x45, new Opcode("LD B,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "L"}) },
            { 0x46, new Opcode("LD B,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "(HL)"}) },
            { 0x47, new Opcode("LD B,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"B", "A"}) },
            { 0x48, new Opcode("LD C,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "B"}) },
            { 0x49, new Opcode("LD C,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "C"}) },
            { 0x4A, new Opcode("LD C,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "D"}) },
            { 0x4B, new Opcode("LD C,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "E"}) },
            { 0x4C, new Opcode("LD C,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "H"}) },
            { 0x4D, new Opcode("LD C,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "L"}) },
            { 0x4E, new Opcode("LD C,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "(HL)"}) },
            { 0x4F, new Opcode("LD C,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"C", "A"}) },
            { 0x50, new Opcode("LD D,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "B"}) },
            { 0x51, new Opcode("LD D,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "C"}) },
            { 0x52, new Opcode("LD D,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "D"}) },
            { 0x53, new Opcode("LD D,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "E"}) },
            { 0x54, new Opcode("LD D,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "H"}) },
            { 0x55, new Opcode("LD D,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "L"}) },
            { 0x56, new Opcode("LD D,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "(HL)"}) },
            { 0x57, new Opcode("LD D,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"D", "A"}) },
            { 0x58, new Opcode("LD E,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "B"}) },
            { 0x59, new Opcode("LD E,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "C"}) },
            { 0x5A, new Opcode("LD E,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "D"}) },
            { 0x5B, new Opcode("LD E,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "E"}) },
            { 0x5C, new Opcode("LD E,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "H"}) },
            { 0x5D, new Opcode("LD E,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "L"}) },
            { 0x5E, new Opcode("LD E,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "(HL)"}) },
            { 0x5F, new Opcode("LD E,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"E", "A"}) },
            { 0x60, new Opcode("LD H,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "B"}) },
            { 0x61, new Opcode("LD H,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "C"}) },
            { 0x62, new Opcode("LD H,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "D"}) },
            { 0x63, new Opcode("LD H,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "E"}) },
            { 0x64, new Opcode("LD H,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "H"}) },
            { 0x65, new Opcode("LD H,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "L"}) },
            { 0x66, new Opcode("LD H,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "(HL)"}) },
            { 0x67, new Opcode("LD H,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"H", "A"}) },
            { 0x68, new Opcode("LD L,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "B"}) },
            { 0x69, new Opcode("LD L,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "C"}) },
            { 0x6A, new Opcode("LD L,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "D"}) },
            { 0x6B, new Opcode("LD L,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "E"}) },
            { 0x6C, new Opcode("LD L,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "H"}) },
            { 0x6D, new Opcode("LD L,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "L"}) },
            { 0x6E, new Opcode("LD L,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "(HL)"}) },
            { 0x6F, new Opcode("LD L,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"L", "A"}) },
            { 0x70, new Opcode("LD (HL),B", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "B"}) },
            { 0x71, new Opcode("LD (HL),C", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "C"}) },
            { 0x72, new Opcode("LD (HL),D", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "D"}) },
            { 0x73, new Opcode("LD (HL),E", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "E"}) },
            { 0x74, new Opcode("LD (HL),H", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "H"}) },
            { 0x75, new Opcode("LD (HL),L", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "L"}) },
            { 0x76, new Opcode("HALT", 1, 4, new OpcodeHandler(MiscOps.HALT), new List<string>{}) },
            { 0x77, new Opcode("LD (HL),A", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(HL)", "A"}) },
            { 0x78, new Opcode("LD A,B", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "B"}) },
            { 0x79, new Opcode("LD A,C", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "C"}) },
            { 0x7A, new Opcode("LD A,D", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "D"}) },
            { 0x7B, new Opcode("LD A,E", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "E"}) },
            { 0x7C, new Opcode("LD A,H", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "H"}) },
            { 0x7D, new Opcode("LD A,L", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "L"}) },
            { 0x7E, new Opcode("LD A,(HL)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(HL)"}) },
            { 0x7F, new Opcode("LD A,A", 1, 4, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "A"}) },
            { 0xAF, new Opcode("XOR A", 1, 4, new OpcodeHandler(ARTHLOG8.XOR), new List<string>{"A"}) },
            { 0xC3, new Opcode("JP a16", 3, 0, 16, new OpcodeHandler(FlowCtrl.JMP), new List<string>{"a16"}) },
            { 0xE0, new Opcode("LDH (a8),A", 2, 12, new OpcodeHandler(LDSTMV8.LDH), new List<string>{"(a8)", "A"}) },
            { 0xE2, new Opcode("LD (C),A", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(C)", "A"}) },
            { 0xEA, new Opcode("LD (a16),A", 3, 16, new OpcodeHandler(LDSTMV8.LD), new List<string>{"(a16)", "A"}) },
            { 0xF0, new Opcode("LDH A,(a8)", 2, 12, new OpcodeHandler(LDSTMV8.LDH), new List<string>{"A", "(a8)"}) },
            { 0xF3, new Opcode("DI", 1, 4, new OpcodeHandler(MiscOps.DI), new List<string>{}) },
            { 0xF2, new Opcode("LD A,(C)", 1, 8, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(C)"}) },
            { 0xFA, new Opcode("LD A,(a16)", 3, 16, new OpcodeHandler(LDSTMV8.LD), new List<string>{"A", "(a16)"}) },
            { 0xFB, new Opcode("EI", 1, 4, new OpcodeHandler(MiscOps.EI), new List<string>{}) },
            { 0xFE, new Opcode("CP d8", 2, 8, new OpcodeHandler(ARTHLOG8.CP), new List<string>{"d8"}) },
        };
    }
}